- name: setup vpn server
  hosts: all
  become: true

  tasks:
  
  - name: install wireguard package
    apt:
      name: wireguard
      state: present
      update_cache: yes

  - name: Generate WireGuard private and public keys
    shell: umask 077 && wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey

  - name: Register WireGuard private key as a variable
    slurp:
      src: /etc/wireguard/privatekey
    register: wg_privatekey

  - name: Register WireGuard public key as a variable
    slurp:
      src: /etc/wireguard/publickey
    register: wg_publickey

  - name: Generate WireGuard configuration file
    template:
        src: wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600
        force: no

  - name: enable and persist ip forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      sysctl_set: yes
      reload: yes

  - name: start wireguard and enable on boot
    systemd:
      name: wg-quick@wg0
      enabled: yes
      state: started